import { ReadmeBuilderConfig } from "@/types/config";

export interface ReadmePreset {
  id: string;
  name: string;
  badge: string;
  icon: string;
  description: string;
  config: Partial<ReadmeBuilderConfig>;
}

export const PRESETS: ReadmePreset[] = [
  {
    id: "fullstack",
    name: "Full-Stack Developer",
    badge: "Popular",
    icon: "💻",
    description: "Modern showcase with tech badges, 3 featured repos, stats cards & contribution graph.",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Hi there",
        typingText: "Full Stack Developer, Open Source Contributor, Tech Enthusiast",
        typingLines: ["Full Stack Developer", "Open Source Contributor", "Tech Enthusiast"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "rounded",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "🟢 Open for work & collaboration",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "👋 Passionate Full Stack Developer building scalable web applications and cloud architecture.",
        workingOn: "Scalable Full Stack Web Applications",
        learning: "Next.js 16, Cloud Native & Microservices",
        collaborateOn: "Developer Tools & React Ecosystem",
        askMeAbout: "TypeScript, React, Node.js, PostgreSQL",
        funFact: "I turn coffee into clean, efficient code!",
        reachMe: "Connect on LinkedIn or send an email",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "JavaScript", "Python", "SQL"],
        frontend: ["React", "Next.js", "Tailwind CSS", "HTML5", "CSS3"],
        backend: ["Node.js", "Express", "NestJS"],
        databases: ["PostgreSQL", "MongoDB", "Redis"],
        mobile: [],
        cloud: ["Vercel", "AWS"],
        devops: ["Docker", "Git", "GitHub Actions"],
        ai: [],
        design: [],
        tools: ["VS Code", "Postman", "npm"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "tokyonight",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      activity: {
        enabled: true,
        showActivityGraph: true,
      },
      sectionOrder: [
        "header",
        "about",
        "skills",
        "socials",
        "projects",
        "stats",
        "contributionGraph",
      ],
    },
  },
  {
    id: "minimalist",
    name: "Minimalist Clean",
    badge: "Clean",
    icon: "✨",
    description: "Sleek, minimal typography focusing on bio, key skills, and top projects.",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Hello, I'm",
        typingText: "Software Engineer",
        typingLines: ["Software Engineer"],
        showTypingSvg: false,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "rounded",
        alignment: "left",
        bannerType: "none",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "",
        showProfileViews: true,
        showStarsBadge: false,
        showFollowersBadge: false,
      },
      about: {
        enabled: true,
        content: "Software Engineer focused on software design, elegance, and high-quality user experiences.",
        workingOn: "Minimalist web applications",
        learning: "System design & performance optimization",
      },
      skills: {
        enabled: true,
        badgeStyle: "flat-square",
        languages: ["TypeScript", "JavaScript", "Go", "Rust"],
        frontend: ["React", "Next.js", "Tailwind CSS"],
        backend: ["Node.js", "Go"],
        databases: ["PostgreSQL", "SQLite"],
        mobile: [],
        cloud: ["Vercel"],
        devops: ["Docker", "Git"],
        ai: [],
        design: [],
        tools: ["VS Code"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: false,
        theme: "radial",
        showStatsCard: false,
        showTopLangsCard: false,
        showStreakCard: false,
        showProfileViews: false,
        showTrophies: false,
        showSnakeGrid: false,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "table",
        selectedRepoIds: [],
        customProjects: [],
      },
      activity: {
        enabled: false,
        showActivityGraph: false,
      },
      sectionOrder: [
        "header",
        "about",
        "skills",
        "socials",
        "projects",
      ],
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk / Dark",
    badge: "Vibrant",
    icon: "🌃",
    description: "Vibrant dark synthwave theme with streak stats, trophies & tech jokes widget.",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Welcome to my hub",
        typingText: "Full Stack Cyber Developer // Open Source Enthusiast",
        typingLines: ["Full Stack Cyber Developer", "Open Source Enthusiast"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "square",
        alignment: "center",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "synthwave",
        statusBadge: "⚡ Hacking the future",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "🌃 Cyberpunk developer crafting futuristic web applications, dark UI interfaces & high performance backends.",
        workingOn: "High throughput distributed systems",
        learning: "WebGPU, Rust & WASM",
        funFact: "I prefer dark mode everywhere!",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "Python", "Rust", "C++"],
        frontend: ["React", "Next.js", "Three.js", "Tailwind CSS"],
        backend: ["Node.js", "FastAPI", "Go"],
        databases: ["PostgreSQL", "Redis"],
        mobile: [],
        cloud: ["Vercel", "AWS"],
        devops: ["Docker", "Kubernetes", "Linux"],
        ai: [],
        design: ["Figma"],
        tools: ["VS Code", "Git"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "synthwave",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: true,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      extras: {
        enabled: true,
        showJokeCard: true,
        showSpotifyWidget: false,
        showWakatime: false,
      },
      activity: {
        enabled: true,
        showActivityGraph: true,
      },
      sectionOrder: [
        "header",
        "about",
        "skills",
        "socials",
        "projects",
        "stats",
        "extras",
        "contributionGraph",
      ],
    },
  },
  {
    id: "ai-data",
    name: "AI & Data Engineer",
    badge: "Specialized",
    icon: "🤖",
    description: "Tailored for AI, Machine Learning & Data Engineers (Python, PyTorch, TensorFlow, Pandas).",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Hi there",
        typingText: "AI Engineer, Data Scientist, ML Practitioner",
        typingLines: ["AI Engineer", "Data Scientist", "ML Practitioner"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "circle",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "🤖 Building AI & Data Pipelines",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "🧠 AI & Data Engineer specializing in Deep Learning, Large Language Models (LLMs), and scalable data pipelines.",
        workingOn: "Autonomous AI Agents & ML Pipelines",
        learning: "LangChain, Vector Databases & Transformer Models",
        askMeAbout: "PyTorch, Python, Model Fine-Tuning, Data Analytics",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["Python", "SQL", "TypeScript", "R"],
        frontend: ["React", "Streamlit"],
        backend: ["FastAPI", "Flask", "Django"],
        databases: ["PostgreSQL", "Redis", "Supabase"],
        mobile: [],
        cloud: ["AWS", "Google Cloud", "Vercel"],
        devops: ["Docker", "Kubernetes", "Linux"],
        ai: ["PyTorch", "TensorFlow", "scikit-learn", "OpenAI", "Hugging Face", "LangChain", "Pandas", "NumPy"],
        design: [],
        tools: ["VS Code", "Git", "Jupyter"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "dracula",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      custom: {
        enabled: true,
        heading: "🤖 AI & ML Research Focus",
        content: "Developing state-of-the-art LLM fine-tuning scripts and real-time inference pipelines.",
      },
      activity: {
        enabled: true,
        showActivityGraph: true,
      },
      sectionOrder: [
        "header",
        "about",
        "skills",
        "socials",
        "projects",
        "stats",
        "custom",
        "contributionGraph",
      ],
    },
  },
];

export function applyPresetToConfig(
  presetId: string,
  currentConfig: ReadmeBuilderConfig
): ReadmeBuilderConfig {
  const preset = PRESETS.find((p) => p.id === presetId);
  if (!preset) return currentConfig;

  const presetConfig = preset.config;

  return {
    ...currentConfig,
    ...presetConfig,
    username: currentConfig.username,
    header: {
      ...currentConfig.header,
      ...(presetConfig.header || {}),
      name: currentConfig.header.name || currentConfig.username,
      avatarUrl: currentConfig.header.avatarUrl,
    },
    about: {
      ...currentConfig.about,
      ...(presetConfig.about || {}),
      content: currentConfig.about.content || presetConfig.about?.content || "",
    },
    socials: {
      ...currentConfig.socials,
      ...(presetConfig.socials || {}),
      github: currentConfig.socials.github || currentConfig.username,
      customLinks: currentConfig.socials.customLinks || [],
    },
    skills: {
      ...currentConfig.skills,
      ...(presetConfig.skills || {}),
      customSkills: currentConfig.skills.customSkills || [],
    },
    projects: {
      ...currentConfig.projects,
      ...(presetConfig.projects || {}),
      selectedRepoIds: currentConfig.projects.selectedRepoIds || [],
      customProjects: currentConfig.projects.customProjects || [],
    },
    custom: {
      ...currentConfig.custom,
      ...(presetConfig.custom || {}),
      content: currentConfig.custom.content || presetConfig.custom?.content || "",
    },
  };
}
