import { ReadmeBuilderConfig } from "@/types/config";

export interface PresetTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  badge: string;
  config: Partial<ReadmeBuilderConfig>;
}

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: "fullstack",
    name: "Full-Stack Dev",
    description: "Modern showcase for web & mobile app developers with tech stack badges, stats & featured repos.",
    icon: "💻",
    badge: "Popular",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Hi there",
        typingText: "Full-Stack Developer, Open Source Enthusiast, Tech Architect",
        typingLines: ["Full-Stack Developer", "Open Source Enthusiast", "Tech Architect"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "rounded",
        alignment: "center",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "🟢 Open for Full-Time Roles & Contracting",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "Passionate software engineer building production-ready web and mobile products. Always curious and eager to learn new technologies.",
        workingOn: "Scalable Microservices & Next.js AI Web Apps",
        learning: "Rust & Advanced Cloud Architecture",
        collaborateOn: "Open-source developer tools",
        askMeAbout: "React, Next.js, Node.js, TypeScript, PostgreSQL",
        funFact: "I brew artisanal espresso while waiting for builds!",
        reachMe: "Connect via LinkedIn or Twitter",
      },
      socials: {
        enabled: true,
        badgeStyle: "for-the-badge",
        github: "",
        linkedin: "",
        twitter: "",
        instagram: "",
        youtube: "",
        facebook: "",
        discord: "",
        email: "",
        portfolio: "",
        customLinks: [],
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "JavaScript", "Python", "HTML5", "CSS3"],
        frontend: ["React", "Next.js", "TailwindCSS", "Redux"],
        backend: ["Node.js", "Express.js", "NestJS"],
        databases: ["PostgreSQL", "MongoDB", "Redis", "Prisma"],
        mobile: ["Flutter", "React Native"],
        cloud: ["Vercel", "AWS"],
        devops: ["Docker", "Git", "GitHub Actions"],
        ai: ["OpenAI"],
        design: ["Figma"],
        tools: ["VS Code", "Postman"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "tokyonight",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
    },
  },
  {
    id: "minimal",
    name: "Minimalist Clean",
    description: "Sleek, typography-focused layout without heavy clutter for senior engineers and researchers.",
    icon: "✨",
    badge: "Clean",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Hello",
        typingText: "Software Engineer & System Designer",
        typingLines: ["Software Engineer & System Designer"],
        showTypingSvg: false,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "circle",
        alignment: "left",
        bannerType: "none",
        bannerUrl: "",
        bannerCapsuleTheme: "soft",
        statusBadge: "",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "Designing resilient distributed systems and elegant developer tools.",
        workingOn: "High throughput backend APIs",
        learning: "Distributed Consensus Algorithms",
        collaborateOn: "",
        askMeAbout: "Go, PostgreSQL, Linux, Kubernetes",
        funFact: "",
        reachMe: "Send an email for inquiries",
      },
      skills: {
        enabled: true,
        badgeStyle: "flat-square",
        languages: ["Go", "TypeScript", "Python", "Rust"],
        frontend: ["React", "TailwindCSS"],
        backend: ["Node.js", "Express.js"],
        databases: ["PostgreSQL", "Redis"],
        mobile: [],
        cloud: ["AWS", "Cloudflare"],
        devops: ["Docker", "Kubernetes", "Git"],
        ai: [],
        design: [],
        tools: ["Linux", "VS Code", "Neovim"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "github_dark",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: false,
        showProfileViews: true,
        showTrophies: false,
        showSnakeGrid: false,
        showDailyQuote: false,
      },
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk / Dark",
    description: "Vibrant synthwave & dark neon aesthetics with activity graphs, stats cards & eye-catching banners.",
    icon: "🌃",
    badge: "Dark Neon",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Greetings Cybernaut",
        typingText: "Full-Stack Cyber Engineer, AI Explorer, Code Architect",
        typingLines: ["Full-Stack Cyber Engineer", "AI Explorer", "Code Architect"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "rounded",
        alignment: "center",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "synthwave",
        statusBadge: "⚡ Hacking on futuristic Web3 & AI tech",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      stats: {
        enabled: true,
        theme: "synthwave",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: true,
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "Python", "Rust", "C++"],
        frontend: ["React", "Next.js", "TailwindCSS"],
        backend: ["Node.js", "FastAPI"],
        databases: ["PostgreSQL", "MongoDB", "Redis"],
        mobile: ["Flutter"],
        cloud: ["Vercel", "AWS"],
        devops: ["Docker", "Git"],
        ai: ["PyTorch", "OpenAI"],
        design: ["Figma"],
        tools: ["VS Code", "Linux"],
        other: [],
        customSkills: [],
      },
    },
  },
  {
    id: "ai_data",
    name: "AI & Data Engineer",
    description: "Tailored for machine learning engineers, data scientists, and AI app builders.",
    icon: "🤖",
    badge: "AI & ML",
    config: {
      header: {
        enabled: true,
        name: "",
        greeting: "Hi, I'm",
        typingText: "AI Researcher, Machine Learning Engineer, Data Specialist",
        typingLines: ["AI Researcher", "Machine Learning Engineer", "Data Specialist"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "",
        avatarStyle: "circle",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "slice",
        statusBadge: "🧠 Fine-tuning LLMs & Multi-Modal Models",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["Python", "TypeScript", "C++", "SQL"],
        frontend: ["React", "Next.js"],
        backend: ["FastAPI", "Flask", "Django"],
        databases: ["PostgreSQL", "MongoDB", "Redis"],
        mobile: [],
        cloud: ["AWS", "Google Cloud"],
        devops: ["Docker", "Git"],
        ai: ["PyTorch", "TensorFlow", "OpenAI", "Pandas", "NumPy", "Scikit-Learn", "Keras"],
        design: [],
        tools: ["VS Code", "Postman", "Linux"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "dracula",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: false,
        showDailyQuote: true,
      },
    },
  },
];
