import { ReadmeBuilderConfig } from "@/types/config";

export interface TemplateItem {
  id: string;
  name: string;
  description: string;
  badge: string;
  icon: string;
  config: Partial<ReadmeBuilderConfig>;
}

export const TEMPLATES: TemplateItem[] = [
  {
    id: "minimal",
    name: "Minimal Developer",
    badge: "Clean",
    icon: "✨",
    description: "Short and clean. Focuses purely on bio, essential tech stack, and top projects without heavy widgets.",
    config: {
      header: {
        enabled: true,
        name: "Alex Vance",
        greeting: "Hello, I'm",
        typingText: "Software Engineer",
        typingLines: ["Software Engineer"],
        showTypingSvg: false,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "rounded",
        alignment: "left",
        bannerType: "none",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "",
        showProfileViews: true,
        showStarsBadge: false,
        showFollowersBadge: false,
      },
      about: {
        enabled: true,
        content: "Software Engineer focused on software design, code elegance, and high-performance systems.",
        workingOn: "Minimal web infrastructure & devtools",
        learning: "Distributed consensus algorithms",
      },
      skills: {
        enabled: true,
        badgeStyle: "flat-square",
        languages: ["TypeScript", "Go", "Rust"],
        frontend: ["React", "Next.js", "Tailwind CSS"],
        backend: ["Node.js", "Go"],
        databases: ["PostgreSQL", "SQLite"],
        mobile: [],
        cloud: ["Vercel"],
        devops: ["Docker", "Git"],
        ai: [],
        design: [],
        tools: ["VS Code"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: false,
        theme: "radial",
        showStatsCard: false,
        showTopLangsCard: false,
        showStreakCard: false,
        showProfileViews: false,
        showTrophies: false,
        showSnakeGrid: false,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "table",
        selectedRepoIds: [],
        customProjects: [],
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects"],
    },
  },
  {
    id: "fullstack",
    name: "Full Stack Developer",
    badge: "Popular",
    icon: "💻",
    description: "Comprehensive layout with header banner, bio bullets, grouped tech stack, stats cards, and project grid.",
    config: {
      header: {
        enabled: true,
        name: "Jordan Lee",
        greeting: "Hi there",
        typingText: "Full Stack Developer, Open Source Contributor",
        typingLines: ["Full Stack Developer", "Open Source Contributor"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "rounded",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "🟢 Open for full-stack opportunities",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "👋 Passionate Full Stack Developer building scalable web applications and cloud services.",
        workingOn: "Scalable SaaS platforms",
        learning: "Next.js 16 & GraphQL",
        collaborateOn: "Open source web projects",
        askMeAbout: "TypeScript, React, Node.js, PostgreSQL",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "JavaScript", "Python", "SQL"],
        frontend: ["React", "Next.js", "Tailwind CSS", "Redux"],
        backend: ["Node.js", "Express", "NestJS"],
        databases: ["PostgreSQL", "MongoDB", "Redis"],
        mobile: [],
        cloud: ["Vercel", "AWS"],
        devops: ["Docker", "Git", "GitHub Actions"],
        ai: [],
        design: [],
        tools: ["VS Code", "Postman", "npm"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "tokyonight",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      activity: {
        enabled: true,
        showActivityGraph: true,
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects", "stats", "contributionGraph"],
    },
  },
  {
    id: "aiEngineer",
    name: "AI / ML Engineer",
    badge: "AI & Data",
    icon: "🤖",
    description: "Tailored for AI, Deep Learning, and Data Science practitioners with PyTorch, TensorFlow & OpenAI stack.",
    config: {
      header: {
        enabled: true,
        name: "Dr. Elena Rostova",
        greeting: "Welcome",
        typingText: "AI Researcher, ML Pipeline Architect",
        typingLines: ["AI Researcher", "ML Pipeline Architect"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "circle",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "🤖 Building LLM Applications",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "🧠 AI & Data Engineer specializing in Deep Learning models, Natural Language Processing, and LLM fine-tuning.",
        workingOn: "Autonomous AI Agents & Vector DB Architecture",
        learning: "LangChain, Transformer Interpretability & Quantization",
        askMeAbout: "PyTorch, Python, Model Deployment, MLOps",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["Python", "SQL", "TypeScript", "R", "C++"],
        frontend: ["React", "Streamlit"],
        backend: ["FastAPI", "Flask"],
        databases: ["PostgreSQL", "Redis", "Supabase"],
        mobile: [],
        cloud: ["AWS", "Google Cloud"],
        devops: ["Docker", "Linux"],
        ai: ["PyTorch", "TensorFlow", "scikit-learn", "OpenAI", "Hugging Face", "LangChain", "Pandas", "NumPy"],
        design: [],
        tools: ["VS Code", "Git"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "dracula",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects", "stats", "contributionGraph"],
    },
  },
  {
    id: "openSource",
    name: "Open Source Developer",
    badge: "Community",
    icon: "🌐",
    description: "Highlights open-source contributions, repository pins, sponsor badges, and active GitHub streak.",
    config: {
      header: {
        enabled: true,
        name: "Marcus Cole",
        greeting: "Hi there",
        typingText: "Open Source Maintainer & Contributor",
        typingLines: ["Open Source Maintainer", "Community Contributor"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "rounded",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "💖 Open source maintainer",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "🌍 Passionate open-source advocate maintaining core developer libraries and CLI tools.",
        workingOn: "Community devtools & rust libraries",
        learning: "WASM & eBPF",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "Rust", "Go", "Python"],
        frontend: ["React", "Next.js"],
        backend: ["Node.js", "Go"],
        databases: ["PostgreSQL"],
        mobile: [],
        cloud: ["Vercel"],
        devops: ["GitHub Actions", "Docker", "Git"],
        ai: [],
        design: [],
        tools: ["VS Code", "npm", "pnpm"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "github_dark",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      sponsors: {
        enabled: true,
        buyMeACoffee: "marcuscole",
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects", "stats", "sponsors", "contributionGraph"],
    },
  },
  {
    id: "student",
    name: "Student Developer",
    badge: "Learning",
    icon: "🎓",
    description: "Great for CS students & Bootcamp grads showcasing projects, learning goals, and social links.",
    config: {
      header: {
        enabled: true,
        name: "Maya Patel",
        greeting: "Hi, I'm",
        typingText: "CS Student @ Tech University | Aspiring Developer",
        typingLines: ["CS Student @ Tech University", "Aspiring Developer"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "circle",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "soft",
        statusBadge: "🎓 Seeking 2026 Internships",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: false,
      },
      about: {
        enabled: true,
        content: "🎓 Computer Science student passionate about web development, data structures, and building real-world projects.",
        workingOn: "Personal portfolio & web projects",
        learning: "Data Structures, Algorithms & Next.js",
        reachMe: "LinkedIn or Email",
      },
      skills: {
        enabled: true,
        badgeStyle: "flat",
        languages: ["Java", "Python", "JavaScript", "HTML5", "CSS3"],
        frontend: ["React", "Bootstrap"],
        backend: ["Node.js", "Express"],
        databases: ["MySQL", "MongoDB"],
        mobile: [],
        cloud: [],
        devops: ["Git"],
        ai: [],
        design: ["Figma"],
        tools: ["VS Code", "Postman"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "nord",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: false,
        showSnakeGrid: false,
        showDailyQuote: true,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects", "stats"],
    },
  },
  {
    id: "designerDeveloper",
    name: "Designer + Developer",
    badge: "Creative",
    icon: "🎨",
    description: "Tailored for UX/UI designers who code (Figma, Photoshop, React, Tailwind, Framer Motion).",
    config: {
      header: {
        enabled: true,
        name: "Chloe Dupont",
        greeting: "Bonjour, I'm",
        typingText: "Design Engineer // UI/UX Designer & Creative Frontend Developer",
        typingLines: ["Design Engineer", "UI/UX Designer & Creative Frontend Developer"],
        showTypingSvg: true,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "rounded",
        alignment: "center",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "slice",
        statusBadge: "🎨 Crafting pixel-perfect UIs",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "🎨 Design Engineer bridging the gap between design systems, typography, and interactive frontend code.",
        workingOn: "Design systems & component libraries",
        learning: "Three.js, WebGL & Shader animation",
      },
      skills: {
        enabled: true,
        badgeStyle: "for-the-badge",
        languages: ["TypeScript", "JavaScript", "HTML5", "CSS3"],
        frontend: ["React", "Next.js", "Tailwind CSS", "Framer Motion", "Three.js"],
        backend: ["Node.js"],
        databases: [],
        mobile: [],
        cloud: ["Vercel"],
        devops: ["Git"],
        ai: [],
        design: ["Figma", "Photoshop", "Illustrator", "Canva"],
        tools: ["VS Code"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "synthwave",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: false,
        showProfileViews: true,
        showTrophies: false,
        showSnakeGrid: false,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "grid",
        selectedRepoIds: [],
        customProjects: [],
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects", "stats"],
    },
  },
  {
    id: "professional",
    name: "Professional",
    badge: "Enterprise",
    icon: "💼",
    description: "Structured corporate/senior engineer layout featuring work experience timeline, credentials & clean bio.",
    config: {
      header: {
        enabled: true,
        name: "David Sterling",
        greeting: "Greetings",
        typingText: "Principal Staff Engineer | Enterprise Solutions Architect",
        typingLines: ["Principal Staff Engineer", "Enterprise Solutions Architect"],
        showTypingSvg: false,
        showAvatar: true,
        avatarUrl: "https://avatars.githubusercontent.com/u/9919?v=4",
        avatarStyle: "rounded",
        alignment: "left",
        bannerType: "none",
        bannerUrl: "",
        bannerCapsuleTheme: "waving",
        statusBadge: "💼 Available for Tech Consulting",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: true,
      },
      about: {
        enabled: true,
        content: "💼 Principal Software Engineer with 10+ years of experience leading engineering teams and building high-volume backend systems.",
        workingOn: "High throughput financial infrastructure",
        askMeAbout: "System Design, Microservices, Cloud Security",
      },
      skills: {
        enabled: true,
        badgeStyle: "flat-square",
        languages: ["Java", "Go", "Python", "TypeScript", "C#", "SQL"],
        frontend: ["React", "Angular"],
        backend: ["Spring", "Node.js", "ASP.NET"],
        databases: ["PostgreSQL", "Oracle", "Redis"],
        mobile: [],
        cloud: ["AWS", "Microsoft Azure"],
        devops: ["Kubernetes", "Docker", "Terraform", "Jenkins"],
        ai: [],
        design: [],
        tools: ["VS Code", "Git"],
        other: [],
        customSkills: [],
      },
      experience: {
        enabled: true,
        items: [
          {
            id: "1",
            role: "Principal Staff Engineer",
            company: "Global Tech Systems",
            period: "2021 - Present",
            description: "Architecting cloud-native microservices handling 50M+ daily requests.",
          },
          {
            id: "2",
            role: "Senior Backend Engineer",
            company: "FinTech Solutions",
            period: "2017 - 2021",
            description: "Developed core transaction processing pipeline in Go and PostgreSQL.",
          },
        ],
      },
      stats: {
        enabled: true,
        theme: "gruvbox",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: false,
        showSnakeGrid: false,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "table",
        selectedRepoIds: [],
        customProjects: [],
      },
      sectionOrder: ["header", "about", "skills", "experience", "socials", "projects", "stats"],
    },
  },
  {
    id: "terminal",
    name: "Terminal / Hacker",
    badge: "Retro",
    icon: "📟",
    description: "Retro dark terminal style README with Linux, Bash, C, Python, and CLI tools focus.",
    config: {
      header: {
        enabled: true,
        name: "root@localhost",
        greeting: "cat ~/welcome.txt",
        typingText: "./init_developer_session.sh --verbose",
        typingLines: ["./init_developer_session.sh --verbose", "exec zsh"],
        showTypingSvg: true,
        showAvatar: false,
        avatarUrl: "",
        avatarStyle: "square",
        alignment: "left",
        bannerType: "capsule",
        bannerUrl: "",
        bannerCapsuleTheme: "synthwave",
        statusBadge: "🟢 System Online 100% Uptime",
        showProfileViews: true,
        showStarsBadge: true,
        showFollowersBadge: false,
      },
      about: {
        enabled: true,
        content: "📟 System programmer & security enthusiast building terminal utilities, Linux kernel modules, and CLI tools.",
        workingOn: "Rust terminal UI applications",
        learning: "Kernel exploitation & low-level networking",
      },
      skills: {
        enabled: true,
        badgeStyle: "plastic",
        languages: ["C", "C++", "Rust", "Python", "Bash", "Assembly"],
        frontend: [],
        backend: ["Go", "Node.js"],
        databases: ["PostgreSQL", "SQLite"],
        mobile: [],
        cloud: ["DigitalOcean"],
        devops: ["Docker", "Linux", "Nginx", "Git"],
        ai: [],
        design: [],
        tools: ["VS Code", "Git"],
        other: [],
        customSkills: [],
      },
      stats: {
        enabled: true,
        theme: "synthwave",
        showStatsCard: true,
        showTopLangsCard: true,
        showStreakCard: true,
        showProfileViews: true,
        showTrophies: true,
        showSnakeGrid: true,
        showDailyQuote: false,
      },
      projects: {
        enabled: true,
        displayStyle: "table",
        selectedRepoIds: [],
        customProjects: [],
      },
      sectionOrder: ["header", "about", "skills", "socials", "projects", "stats", "contributionGraph"],
    },
  },
];
